In [1]:
# 매 강의 시작시마다 동일하게 처리해야 함
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:10pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:10pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:10pt;padding:5px;}
table.dataframe{font-size:15px;
</style>
"""))

In [ ]:
# 4/16

In [13]:
def my_hello():
    '''
    sllkjflksdjflsdkjfljsdf
    slfkjsldkjflsdkjflskfj
    skdflsdjf
    '''
    print('hello world')

In [14]:
print(my_hello())

hello world
None


In [16]:
def fibonacci(n):
    a, b = 0, 1
    while a < n:
        print(a, end='   ')
        a, b = b, a + b
    print()


In [18]:
print(fibonacci(50))

0   1   1   2   3   5   8   13   21   34   
None


In [20]:
global_var = 100
def func1():
    print('함수안 :', global_var)
func1()
print('함수밖 :', global_var)

함수안 : 100
함수밖 : 100


In [21]:
g_var = 100
def func2():
    local_var = 20
    print('함수안:', local_var)
func2()
print('함수밖:', local_var)

함수안: 20


NameError: name 'local_var' is not defined

In [22]:
def tot(x,y):
    return x + y

In [24]:
print(tot(3,4))

7


In [27]:
def add():
    return False

In [28]:
print(add())

False


In [31]:
def add(*args):
    result_tot = 0
    for data in args:
        result_tot += data
    return result_tot

In [32]:
print(add(1,2,3,43,45,))

94


In [35]:
subject = 'a', 'b', 'd', 'd'
def concat(*subject, sep):
    return sep.join(subject)


In [43]:
def add(a,b):
    return a+b

In [44]:
print(add(3,4))

7


In [47]:
add2 = lambda a,b : a+b
add3 = lambda c,d : c *d
print(add3(4,5))

20


In [49]:
def diff(a):
    return "홀수" if a%2 else "짝수"
    

In [51]:
print(diff(3))

홀수


In [52]:
def diff2(a,b):
    return a-b if a>b else b-a
    return result

In [53]:
print(diff2(3,7))

4


In [54]:
ex2 = lambda a, b : a-b  if a>b else b-a

In [57]:
print(ex2(4000,-500))

4500


In [58]:
ex3 = lambda a : a if a>=0 else 'negative'

In [59]:
print(ex3(4000))

4000


In [60]:
ex4 = lambda score : 'a team' if 80<=score<=100 else \
                    'b team' if 60<=score<=80 else \
                    're exam' if 0<=score<60 else \
                    'ding'

In [64]:
print(ex4(60))

b team


In [2]:
def number():
    chk_num = int(input("숫자를 입력해주세요:"))
    if chk_num % 2 == 0:
        print("짝수입니다.")
    else:
        print("홀수입니다.")



In [3]:
number()

숫자를 입력해주세요:3
홀수입니다.


In [12]:
def nums():
    a = int(input("첫번째숫자 입력:"))
    b = int(input("두번째숫자 입력:"))
    if a > b:
        print("{}이 {}보다 큽니다.".format(a,b))
    elif a < b:
        print("{}이 {}보다 작습니다.".format(a,b))
    else:
        print("{}와 {}는 같습니다..".format(a,b))

In [14]:
nums()


첫번째숫자 입력:4
두번째숫자 입력:3
4이 3보다 큽니다.


In [15]:
def text_test():
    t = input("글자 입력:")
    print(len(t))
    

text_test()
    

글자 입력:rksmssdfsdf sdf
15


In [24]:
def avg():
    num1 = int(input("1 number:"))
    num2 = int(input("2 number:"))
    num3 = int(input("3 number:"))
    num_avg = (num1+num2+num3)/3
    print(round(num_avg,2))
    

In [25]:
avg()

1 number:3
2 number:5
3 number:6
4.67


In [30]:
def aaa():
    num1 = int(input("1st :"))
    num2 = int(input("2st :"))
    num3 = int(input("3st :"))
    tot = (num1 + num2 + num3)/3
    if tot >= 90:
        print("수")
    elif tot >= 80:
        print("우")
    elif tot >= 70:
        print("미")
    else:
        print("재시험")
    
aaa()

1st :50
2st :80
3st :90
우


In [32]:
def grade():
    scores = [int(input(f"{i+1}번째 과목 점수:")) for i in range(3)]
    avg = sum(scores) / len(scores)
    
    if avg >= 90 :
        grade = "수"
    elif avg >= 80 :
        grade = "우"
    elif avg >= 70 :
        grade = "미"
    else:
        grade = "재시험"
    print(f"평균은 {avg:.2f}점이고, 등급은 {grade}입니다.")
    
    
grade()
        
    

1번째 과목 점수:30
2번째 과목 점수:40
3번째 과목 점수:50
평균은 40.00점이고, 등급은 재시험입니다.


In [35]:
def grade_level():
    a, b, c = int(input()), int(input()), int(input())
    avg = (a + b + c)/3
    print("수" if avg >= 90 else "우" if avg >= 80 else "미" if avg >= 70 else "재시험")
    
grade_level()

1
2
3
재시험


In [39]:
def max_num():
    lst = list(map(int, input().split()))
    print(f"최대값:{max(lst)}, 최소값{min(lst)}")

max_num()
          
    

30 90 50 60
최대값:90, 최소값30


In [43]:
def max_num():
    lst = list(map(int, input().split()))
    print("최대값:{}, 최소값:{}".format(max(lst),min(lst)))

max_num()

50 80 70 40
최대값:80, 최소값:40


In [10]:
def jjaksu():
    lst = list(map(int,input("숫자 입력 공백구분 여러개").split()))
    for num in lst:
        if num %2==0:
            print(num)

jjaksu()        
    

숫자 입력 공백구분 여러개12 21 34 23 235 23432 23 
12
34
23432


In [11]:
def holsu():
    lst = list(map(int, input("숫자, 공백, 여려개").split()))
    for num in lst:
        if num%2 != 0:
            print(num)

holsu()
    

숫자, 공백, 여려개12 32 42 55432 3423464567 4 4654 5456 4 6745 654 6456 
3423464567
6745


In [17]:
def holsu():
    lst = list(map(int, input("숫자, 공백, 여려개").split()))
    result = []
    for num in lst:
        if num%2 != 0:
            result.append(num)
    print(result)
            

holsu()

숫자, 공백, 여려개23 234 562345 234 24 34 235 23 2 34 234 234 
[23, 562345, 235, 23]


In [20]:
def holsu():
    print([x for x in map(int, input().split()) if x%2 !=0])

In [21]:
holsu()

924 23432 4 25 4 3543 5 
[25, 3543, 5]


# 4/23

In [23]:
np.array([1,2,3])

NameError: name 'np' is not defined

In [26]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [33]:
print(arr.ndim, arr.shape, arr.size, arr.dtype)

1 (5,) 5 int32


In [36]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
tot = arr1 + arr2
print(tot)


[11 22 33]


In [39]:
print(np.array([1,2,3])+np.array([10,20,30]))

[11 22 33]


In [42]:
print(np.array([1,2,3])**2)

[1 4 9]


In [43]:
# 브로드캐스팅
# 차원이 다른 배열끼리도 자동으로 맞춰서 연산할 수 있는 기능

In [44]:
a = np.array([2,3,4,5,6])
b = 5
print(a*b)

[10 15 20 25 30]


In [45]:
a = np.array([[1],[2],[3]])
b = 3
print(a+b)

[[4]
 [5]
 [6]]


In [46]:
a = np.array([1,2,3])
b = 10
print(a+b)

[11 12 13]


In [47]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [54]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a[1])
print(a[1:,:2])
print(a[2,:1])

[4 5 6]
[[4 5]
 [7 8]]
[7]


In [73]:
print(a[2,:2])

[7 8]


In [75]:
a = np.array([1,3,5,7,9])
cond = a[a>5]
print(cond)

[7 9]


In [77]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = a[a>5]
print(b)

[6 7 8 9]


In [79]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = a[a>5] = 3
print(a)

[[1 2 3]
 [4 5 3]
 [3 3 3]]


In [ ]:
arr.ndim     # 차원 수
arr.shape    # 구조 (행, 열)
arr.size     # 전체 요소 개수
arr.dtype    # 자료형